baseurl         = "https://willowbark.org"
languageCode    = "en-us"
title           = "Willow Bark Co-op"
theme           = "salix"
enableRobotsTXT = true

[author]

name  = "Willow Bark Co-op"
email = "hello@example.net"

[params]

# logo      = ""
description = """a small co-operative team of designers & developers working
on open and decentralised technology."""

[params.contact]

org   = "Willow Bark Co-op"
email = "hello@example.net"
