baseurl         = "https://willowbark.org"
languageCode    = "en-us"
title           = "Willow Bark Co-op"
theme           = "salix"
enableRobotsTXT = true

[author]

name  = "Willow Bark Co-op"
email = "hello@example.net"

[params]

# logo      = ""
description = """a co-operative team of designers & developers building
better software for a better world."""

[params.contact]

org   = "Willow Bark Co-op"
email = "hello@willowbark.org"
